export const plants = [
  {
    id: 1,
    name: "Monstera",
    picture: "/images/plant1.jpg",
    type: "Indoor",
    price: 55,
  },
  {
    id: 2,
    name: "Aloe Vera",
    picture: "/images/plant2.jpg",
    type: "Indoor",
    price: 37,
  },
  {
    id: 3,
    name: "Snake Plant",
    picture: "/images/plant3.jpg",
    type: "Indoor",
    price: 45,
  },
  {
    id: 4,
    name: "Dracaena",
    picture: "/images/plant4.jpg",
    type: "Outdoor",
    price: 127,
  },
  {
    id: 5,
    name: "Coffee Plant",
    picture: "/images/plant4.jpg",
    type: "Organic",
    price: 20,
  },
  {
    id: 6,
    name: "Spruce Tree",
    picture: "/images/plant4.jpg",
    type: "Garden",
    price: 35,
  },
  {
    id: 7,
    name: "Succulent",
    picture: "/images/plant4.jpg",
    type: "Outdoor",
    price: 25,
  },
  {
    id: 8,
    name: "Milkweed",
    picture: "/images/plant4.jpg",
    type: "Organic",
    price: 25,
  },
  {
    id: 9,
    name: "Sunflower",
    picture: "/images/plant4.jpg",
    type: "Garden",
    price: 35,
  },
  {
    id: 10,
    name: "Rosemary",
    picture: "/images/plant4.jpg",
    type: "Outdoor",
    price: 15,
  },
  {
    id: 11,
    name: "Mint",
    picture: "/images/plant4.jpg",
    type: "Organic",
    price: 18,
  },
  {
    id: 12,
    name: "Tomato",
    picture: "/images/plant4.jpg",
    type: "Garden",
    price: 12,
  },
];